// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdjjpnkkblnpvvruaxpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkampwbmtrYmxucHZ2cnVheHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDMwODEsImV4cCI6MjA3MzExOTA4MX0.tlHVhoQP6ThRxFwrOPgHsQnt_uJ1W7Qpt-z8rEWisQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});